### ISSUE TITLE
Failure to build on 64 bit linux (gentoo-hardened non multi-lib)

### ISSUE THREAD

**Issue by vyrus001** [wireapp/wire-desktop#1750]
Wire version: <Check the About dialog> Wire for web version: <Check the About dialog> Operating system: <OS/distribution and version number> Which antivirus software do you have installed: <This helps us to find out if there are compatibility issues with antivirus software>

What steps will reproduce the problem?

attempt to compile the Linux application on an x86_64 bit system

What is the expected result?

The application will compile

What is the actual result?

The following error snipit

Running "electronbuilder:linux_prod" (electronbuilder) task
  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=wrap/dist/builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=ia32
Warning: /usr/local/bin/node exited with code 1
Output:

> spellchecker@3.5.0 install /home/{USER}/tools/wire-desktop/electron/node_modules/spellchecker
> node-gyp rebuild

make: Entering directory '/home/{USER}/tools/wire-desktop/electron/node_modules/spellchecker/build'
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affentry.o
make: Leaving directory '/home/{USER}/tools/wire-desktop/electron/node_modules/spellchecker/build'

Error output:
In file included from /usr/include/features.h:452,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/x86_64-pc-linux-gnu/bits/os_defines.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/x86_64-pc-linux-gnu/bits/c++config.h:508,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/cstdlib:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/stdlib.h:36,
                 from ../vendor/hunspell/src/hunspell/affentry.cxx:4:
/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
           ^~~~~~~~~~~~~~~~
compilation terminated.
make: * [hunspell.target.mk:104: Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affentry.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.9.24-hardened
gyp ERR! command "/usr/local/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/{USER}/tools/wire-desktop/electron/node_modules/spellchecker
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.9.24-hardened
npm ERR! argv "/usr/local/bin/node" "/usr/lib64/node_modules/npm/bin/npm-cli.js" "rebuild" "node-addressbook@1.2.0" "spellchecker@3.5.0"
npm ERR! node v10.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! spellchecker@3.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spellchecker@3.5.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spellchecker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/{USER}/tools/wire-desktop/electron/npm-debug.log
 Use --force to continue.

Please provide any additional information below. Attach a screenshot if possible.

The error appears to be that stubs.h attempts to include stubs-32.h and I am on a non mult-lib x64 system. stubs-64.h exists but the 32 bit version does not.

**Comment by ffflorian** [comment]
Hi @vyrus001, this seems to be a problem with missing libraries on your system. Can you check if this helps? https://stackoverflow.com/a/7412698

**Comment by vyrus001** [comment]
no, the lib isn't "missing", the 32 bit .h file isn't there because my system is not a multi-lib system (64/32 bit) its 64 only and there does not seem to be a flag I can add to the build command to NOT build multi-lib

**Comment by ffflorian** [comment]
Yes, it's not missing for your system, but it's missing to build wire-desktop. :slightly_smiling_face:

**Comment by ffflorian** [comment]
@vyrus001 are there more questions regarding building wire-desktop or can I close this issue?

**Comment by ffflorian** [comment]
Closing this due to inactivity.
