### ISSUE TITLE
wire does not start - error

### ISSUE THREAD

**Issue by bagiwi** [wireapp/wire-desktop#3033]
This error occurs when trying to start app image on linux latest wire version:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)
    at handlePortableFlags (/tmp/******/resources/app/electron/dist/main.js:340:30)
    at Object.<anonymous> (/tmp/******/resources/app/electron/dist/main.js:465:1)
    at Object.<anonymous> (/tmp/******/resources/app/electron/dist/main.js:477:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

**Comment by ffflorian** [comment]
@bagiwi which version of Wire are you using?

**Comment by gv2os** [comment]
@ffflorian this error occurs when using --portable option with Wire 3.10.2904 - Linux app image

**Comment by gv2os** [comment]
@ffflorian might be similar : https://github.com/wireapp/wire-desktop/issues/1554

it could be a good idea to remember this for all future releases because it seems that this is the second time this is occuring
