### ISSUE TITLE
Any chance of an ARM version?

### ISSUE THREAD

**Issue by Strit** [wireapp/wire-desktop#314]
Hi all.

I was just wondering, since all the dependencies support ARM, but the Wire-Desktop app is either x64_86 or i686 specific (at least for the Linux version), would it be possible to add ARM support in the Wire software?

I see these lines in the PKGBUILD for Arch Linux:
```
  if [ $CARCH == 'x86_64' ]; then
    node_modules/.bin/build --linux --x64 --dir
  elif [ $CARCH == 'i686' ]; then
    node_modules/.bin/build --linux --ia32 --dir
  else
    echo "Unknown architecture"; exit 1;
  fi
```

Possible to add like:
`node_modules/.bin/build --linux --arm/armv7/armv6/aarch64 --dir
`
To those?

I don't know how node_modules work, which is why I ask.

**Comment by ConorIA** [comment]
I am the maintainer of the Arch PKGBUILD. 
Please try building Wire with the following: 

``` shell
yarn
grunt 'clean:linux' 'update-keys' 'release-prod'
node_modules/.bin/build --linux --armv7l  --dir
```

If everything builds ok, please test the build by running:
``` shell
<I will edit this in in a minute>
```

If everything works for you, I will be happy to update the PKGBUILD to include the build for ARMv7l devices.

**Comment by Strit** [comment]
I'll try this, next time I'm at my arm device. Thanks.

**Comment by Strit** [comment]
This is what I get when running the "yarn" command.

```
Traceback (most recent call last):
  File "/usr/lib/node_modules/yarn/node_modules/node-gyp/gyp/gyp_main.py", line                                                                              16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/lib/node_modules/yarn/node_modules/node-gyp/gyp/pylib/gyp/__init__.                                                                             py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/lib/node_modules/yarn/node_modules/node-gyp/gyp/pylib/gyp/__init__.                                                                             py", line 538, in main
    return gyp_main(args)
  File "/usr/lib/node_modules/yarn/node_modules/node-gyp/gyp/pylib/gyp/__init__.                                                                             py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/lib/node_modules/yarn/node_modules/node-gyp/gyp/pylib/gyp/__init__.                                                                             py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/usr/lib/node_modules/yarn/node_modules/node-gyp/gyp/pylib/gyp/input.py"                                                                             , line 2775, in Load
    variables, includes, depth, check, True)
  File "/usr/lib/node_modules/yarn/node_modules/node-gyp/gyp/pylib/gyp/input.py"                                                                             , line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/usr/lib/node_modules/yarn/node_modules/node-gyp/gyp/pylib/gyp/input.py"                                                                             , line 1214, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "/usr/lib/node_modules/yarn/node_modules/node-gyp/gyp/pylib/gyp/input.py"                                                                             , line 1225, in ProcessVariablesAndConditionsInDict
    'only, found ' + expanded.__class__.__name__ + ' for ' + key)
ValueError: Variable expansion in this context permits str and int only, found l                                                                             ong for lastUpdateCheck while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/yarn/node_mod                                                                             ules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                             s.js:215:12)
gyp ERR! System Linux 3.10.104-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/yarn/node_modules/node-g                                                                             yp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/strit/wire-desktop-release-2.11.2686/node_modules/nslog
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```

The $CARCH's are armv7h, armv6h and aarch64 for the devices I have.

**Comment by ConorIA** [comment]
The above seems to be an error within gyp itself, and is possible related to this: https://github.com/nodejs/node-gyp/issues/903. Maybe weigh-in with an issue post on that repo and see what they recommend.
