### ISSUE TITLE
Build fails without a git repository

### ISSUE THREAD

**Issue by sometoby** [wireapp/wire-desktop#3411]
When building wire-desktop from a source tree that isn't a git repository (e.g. using the source tarballs attached to the GitHub releases), the following failure occurs:

```
yarn run v1.21.1
$ yarn build:prepare && ts-node -P tsconfig.bin.json ./bin/build-tools/build-cli.ts linux
$ yarn clear:wrap && yarn build:ts && yarn bundle
$ rimraf wrap
$ yarn clear:ts && tsc
$ rimraf electron/dist
$ webpack --env.production
❌  @wireapp/build-tools::build-cli [2020-01-05 04:58:45] Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at Pipe.<anonymous> (net.js:658:12) {
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git rev-parse --short HEAD',
  stdout: '',
  stderr: 'fatal: not a git repository (or any of the parent directories): .git\n'
}
```

**Comment by ffflorian** [comment]
Thanks for the notification @sometoby! This was fixed in https://github.com/wireapp/wire-desktop/pull/3427 and will be applied with the next merge to master (aka next release).

Until then, please do the following before running `yarn`:
```bash
git init
git -c user.name="FIXME" -c user.email="FIXME" commit --allow-empty -m "FIXME"
```

(taken from [the Arch Linux build script](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/wire-desktop))
