### ISSUE TITLE
JavaScript error window pops up

### ISSUE THREAD

**Issue by f4th0m** [wireapp/wire-desktop#3973]
Wire version: 3.19.0_11079ac3.0_11079ac3-1
Wire for web version: 3.19
Operating system: Linux/Mageia Cauldron
Which antivirus software do you have installed: clamd

What steps will reproduce the problem?

1.  git clone 
2.  yarn
3.  yarn:build
4.  install rpm
5.  Javascript error pops up, Wire-desktop does not starrt up, process keeps up

What is the expected result?
Working wire messenger
...

What is the actual result?
process does not halt, javascript error pops up ,Wire does not start
...

Please provide any additional information below. Attach a screenshot if possible.

...
![kép](https://user-images.githubusercontent.com/15020214/84667553-ce1d5880-af22-11ea-857f-1e6e57ae37ec.png)

**Comment by CanuteTheGreat** [comment]
I too am experiencing this:
git clone ...
yarn
yarn start
<snipped>
App threw an error during load
TypeError: Cannot read property 'match' of undefined
    at Object.exports.getText (/home/canutethegreat/Downloads/wire/wire-desktop/electron/dist/locale/locale.js:104:17)
    at Object.<anonymous> (/home/canutethegreat/Downloads/wire/wire-desktop/electron/dist/menu/system.js:217:19)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
[1066401:0617/113812.943378:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
<snipped>

Process hangs at this point.

![wire-error](https://user-images.githubusercontent.com/12352246/84937060-0d1cec80-b090-11ea-8b72-cf3113a5477c.png)

**Comment by f4th0m** [comment]
Latest version has the same JS error, plus the below thrown to the console:
[fathom@northernlights wire-desktop (dev)]$ yarn start
yarn run v1.22.4
$ yarn build:ts && yarn bundle:dev
$ yarn clear:ts && tsc
$ rimraf electron/dist
$ webpack
$ cross-env NODE_DEBUG=@wireapp* electron . --no-sandbox --inspect --devtools --enable-logging
Debugger listening on ws://127.0.0.1:9229/680a74d4-5063-4d04-9bd9-daee3d65d895
For help, see: https://nodejs.org/en/docs/inspector
ℹ️  @wireapp/desktop/ConfigurationPersistence [2020-06-21 21:38:17] Reading config file from "/home/fathom/.config/Wire/config/init.json" ...
ℹ️  @wireapp/desktop/ConfigurationPersistence [2020-06-21 21:38:17] Initializing ConfigurationPersistence
ℹ️  @wireapp/desktop/ConfigurationPersistence [2020-06-21 21:38:17] Restoring "locale"
ℹ️  @wireapp/desktop/ConfigurationPersistence [2020-06-21 21:38:17] Restoring "env"
ℹ️  @wireapp/desktop/ConfigurationPersistence [2020-06-21 21:38:17] Restoring "showMenu"
ℹ️  @wireapp/desktop/ConfigurationPersistence [2020-06-21 21:38:17] Restoring "shouldAutoLaunch"
App threw an error during load
TypeError: Cannot read property 'match' of undefined
    at Object.exports.getText (/home/fathom/Letöltések/wire-desktop/electron/dist/locale/locale.js:104:17)
    at Object.<anonymous> (/home/fathom/Letöltések/wire-desktop/electron/dist/menu/system.js:217:19)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
[808734:0621/233817.774804:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[808734:0621/233817.787396:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.787595:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.787782:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.788053:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.788176:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.788280:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.788381:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.788459:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.788525:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.788666:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.788895:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.788996:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.789109:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.789205:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.789293:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.789777:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.789985:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790084:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790157:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790272:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790346:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790411:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790644:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790720:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790788:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790855:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790918:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.790978:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.791045:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.791121:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.791528:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)
[808734:0621/233817.791647:ERROR:gbm_wrapper.cc(271)] Failed to export buffer to dma_buf: Nincs ilyen fájl vagy könyvtár (2)

**Comment by ffflorian** [comment]
Fixed in b18649c88edeecc4ca402685e1647982f3a2be22.
