### ISSUE TITLE
[Solved] Multiple build problems on linux

### ISSUE THREAD

**Issue by RichardWilliamPearse** [wireapp/wire-desktop#425]
Solved: on linux, the package nodejs-legacy is required. This is to link /usr/bin/node to node.js or some such.  I also installed node-number-is-nan. 

Now there is another error. I will open a separate issue for that.

---------------------------

[ This is now solved ]

I know nothing about node.js or npm (I installed both only to try out wire). 

As instructed I 

* git clone https://github.com/wireapp/wire-desktop.git
* cd wire-desktop/
* npm install

and got this/these response(s):

```
wire-desktop@ preinstall /.hw/home/bench/system/toInstall/messaging/wire-desktop
 cd electron && npm install
     
 npm WARN package.json open-graph@0.2.1 license should be a valid SPDX license expression
 npm WARN package.json raygun@0.9.0 No license field.
    
> node-addressbook@1.2.0 install /.hw/home/bench/system/toInstall/messaging/wire-desktop/electron/node_modules/node-addressbook
> node-gyp rebuild
    
/bin/sh: 1: node: Permission denied
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.9.0-1-686-pae
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /.hw/home/bench/system/toInstall/messaging/wire-desktop/electron/node_modules/node-addressbook
gyp ERR! node -v v4.7.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian


> spellchecker@3.3.1 install /.hw/home/bench/system/toInstall/messaging/wire-desktop/electron/node_modules/spellchecker
> node-gyp rebuild

/bin/sh: 1: node: Permission denied
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.9.0-1-686-pae
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /.hw/home/bench/system/toInstall/messaging/wire-desktop/electron/node_modules/spellchecker
gyp ERR! node -v v4.7.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional dep failed, continuing node-addressbook@1.2.0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! spellchecker@3.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spellchecker@3.3.1 install script.
npm ERR! This is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.9.0-1-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /.hw/home/bench/system/toInstall/messaging/wire-desktop/electron
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /.hw/home/bench/system/toInstall/messaging/wire-desktop/electron/npm-debug.log
npm ERR! not ok code 0

npm ERR! wire-desktop@ preinstall: `cd electron && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wire-desktop@ preinstall script.
npm ERR! This is most likely a problem with the wire-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd electron && npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls wire-desktop
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.0-1-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /.hw/home/bench/system/toInstall/messaging/wire-desktop
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /.hw/home/bench/system/toInstall/messaging/wire-desktop/npm-debug.log
npm ERR! not ok code 0
```

----------------------

The npm-debug.log is

```0 info it worked if it ends with ok
 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
 2 info using npm@1.4.21
 3 info using node@v4.7.2
 4 verbose readDependencies using package.json deps
 5 verbose install where, deps [ '/.hw/home/bench/system/toInstall/messaging/wire-desktop',
 5 verbose install   [ 'electron',
 5 verbose install     'electron-builder',
 5 verbose install     'electron-mocha',
 5 verbose install     'electron-packager',
 5 verbose install     'electron-rebuild',
 5 verbose install     'eslint',
 5 verbose install     'grunt',
 5 verbose install     'grunt-contrib-clean',
 5 verbose install     'grunt-electron-installer',
 5 verbose install     'grunt-git',
 5 verbose install     'grunt-github-changes',
 5 verbose install     'grunt-shell',
 5 verbose install     'load-grunt-tasks' ] ]
 6 info preinstall wire-desktop@
 7 verbose unsafe-perm in lifecycle true
 8 info wire-desktop@ Failed to exec preinstall script
 9 error wire-desktop@ preinstall: `cd electron && npm install`
 9 error Exit status 1
 10 error Failed at the wire-desktop@ preinstall script.
 10 error This is most likely a problem with the wire-desktop package,
 10 error not with npm itself.
 10 error Tell the author that this fails on your system:
 10 error     cd electron && npm install
 10 error You can get their info via:
 10 error     npm owner ls wire-desktop
 10 error There is likely additional logging output above.
 11 error System Linux 4.9.0-1-686-pae
 12 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
 13 error cwd /.hw/home/bench/system/toInstall/messaging/wire-desktop
 14 error node -v v4.7.2
 15 error npm -v 1.4.21
 16 error code ELIFECYCLE
 17 verbose exit [ 1, true ]
```
---------

Feel free to ask me any questions. 

Note that I have installed the debian/apt package 'node-number-is-nan' and this does not have effect: the errors are still exactly the same

**Comment by ConorIA** [comment]
It is a little broad to say "problems" on Linux. What platform were you using? Debian-based distros often need the latest version of NodeJS from the Node website (the version in the repo is too old). I'm having no trouble on Manjaro with: 

```
$ node -v
v7.4.0
$ npm -v
4.1.2
```

**Comment by lipis** [comment]
If this is solved.. can you close it?
