### ISSUE TITLE
Found incomatible module fs-extra

### ISSUE THREAD

**Issue by lofmat** [wireapp/wire-desktop#4857]
Wire version: 3.22.2937
Operating system: Ubuntu 18.04.5 LTS

What steps will reproduce the problem?

1.  Download wire-desktop-linux-3.22.2937.zip from [here](https://github.com/wireapp/wire-desktop/tags)
2.  unzip wire-desktop-linux-3.22.2937.zip
3.  cd wire-desktop-linux-3.22.2937
4. yarn --verbose

What is the expected result?

wire-desktop successfully installed

What is the actual result?

```
error fs-extra@9.0.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.10.0"
verbose 1.642 Error: Found incompatible module.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at checkOne (/usr/local/lib/node_modules/yarn/lib/cli.js:48059:11)
    at Object.check (/usr/local/lib/node_modules/yarn/lib/cli.js:48078:5)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:7348:73
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at <anonymous>
error Found incompatible module.
```

**Comment by ffflorian** [comment]
Hi @lofmat,

as you can read in the error message, you'll need at least Node.js 10 to build the app.

**Comment by lofmat** [comment]
@ffflorian thank you for your reply.
