### ISSUE TITLE
Wire Desktop for Linux build error while loading shared libraries: libbz2.so.1.0

### ISSUE THREAD

**Issue by 1div0** [wireapp/wire-desktop#532]
$ npm run build:linux

> wire-desktop@ build:linux /usr/src/wireapp/wire-desktop
> grunt linux-prod

Running "clean:linux" (clean) task
>> 3 paths cleaned.

Running "update-keys" task

Running "release-prod" task
Releases URL points to https://wire-app.wire.com/win/prod/ OK

Running "shell:linux64" (shell) task
Rebuilding native production dependencies for linux:x64
Warning: Packaging using asar archive is disabled — it is strongly not recommended.
Please enable asar and use asarUnpack to unpack files that must be externally available.
Packaging for linux x64 using electron 1.6.4 to wrap/dist/linux-unpacked
Building AppImage for arch x64
Error: Exit code: 127. Command failed: /home/nct/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /usr/src/wireapp/wire-desktop/wrap/dist/wire-2.13.2734-x86_64.AppImage -padding 0 -map /usr/src/wireapp/wire-desktop/wrap/dist/linux-unpacked /usr/bin -map /usr/src/wireapp/wire-desktop/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-M2guFC/0-2-Wire.desktop /wire.desktop -map /usr/src/wireapp/wire-desktop/resources/icons/256x256.png /usr/share/icons/default/256x256/apps/wire.png -map /usr/src/wireapp/wire-desktop/resources/icons/32x32.png /usr/share/icons/default/32x32/apps/wire.png -map /usr/src/wireapp/wire-desktop/resources/icons/256x256.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
/home/nct/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

/home/nct/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
From previous event:
    at exec (/usr/src/wireapp/wire-desktop/node_modules/electron-builder-util/src/util.ts:53:3)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/targets/appImage.ts:79:11
    at next (native)
From previous event:
    at AppImageTarget.build (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/targets/appImage.js:142:11)
    at postAsyncTasks.push.default.map.it (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/platformPackager.ts:103:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/platformPackager.ts:103:41)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/platformPackager.ts:99:10
From previous event:
    at LinuxPackager.pack (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/platformPackager.js:160:11)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/packager.ts:210:22
From previous event:
    at Packager.doBuild (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/packager.js:335:11)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/packager.ts:151:38
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/packager.js:261:11)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/builder.ts:214:40
    at next (native)
From previous event:
    at build (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Warning: Command failed: build --linux --x64
Error: Exit code: 127. Command failed: /home/nct/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /usr/src/wireapp/wire-desktop/wrap/dist/wire-2.13.2734-x86_64.AppImage -padding 0 -map /usr/src/wireapp/wire-desktop/wrap/dist/linux-unpacked /usr/bin -map /usr/src/wireapp/wire-desktop/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-M2guFC/0-2-Wire.desktop /wire.desktop -map /usr/src/wireapp/wire-desktop/resources/icons/256x256.png /usr/share/icons/default/256x256/apps/wire.png -map /usr/src/wireapp/wire-desktop/resources/icons/32x32.png /usr/share/icons/default/32x32/apps/wire.png -map /usr/src/wireapp/wire-desktop/resources/icons/256x256.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
/home/nct/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

/home/nct/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
From previous event:
    at exec (/usr/src/wireapp/wire-desktop/node_modules/electron-builder-util/src/util.ts:53:3)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/targets/appImage.ts:79:11
    at next (native)
From previous event:
    at AppImageTarget.build (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/targets/appImage.js:142:11)
    at postAsyncTasks.push.default.map.it (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/platformPackager.ts:103:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/platformPackager.ts:103:41)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/platformPackager.ts:99:10
From previous event:
    at LinuxPackager.pack (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/platformPackager.js:160:11)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/packager.ts:210:22
From previous event:
    at Packager.doBuild (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/packager.js:335:11)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/packager.ts:151:38
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Packager.build (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/packager.js:261:11)
    at /usr/src/wireapp/wire-desktop/node_modules/electron-builder/src/builder.ts:214:40
    at next (native)
From previous event:
    at build (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/usr/src/wireapp/wire-desktop/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
 Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.8.15-300.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:linux"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! wire-desktop@ build:linux: `grunt linux-prod`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the wire-desktop@ build:linux script 'grunt linux-prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wire-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt linux-prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wire-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wire-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/wireapp/wire-desktop/npm-debug.log

$ rpm -ql bzip2-libs
**/usr/lib64/libbz2.so.1
/usr/lib64/libbz2.so.1.0.6**
/usr/share/licenses/bzip2-libs
/usr/share/licenses/bzip2-libs/LICENSE

[npm-debug.log.txt](https://github.com/wireapp/wire-desktop/files/867819/npm-debug.log.txt)

**Comment by 1div0** [comment]
Quick & dirty fix

# ln -s libbz2.so.1.0.6 libbz2.so.1.0

**Comment by ffflorian** [comment]
Seems like this is a known bug in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=461863

**Comment by 1div0** [comment]
However it is CLOSED NOTABUG

**Comment by ConorIA** [comment]
@1div0, even if it won't be fixed on the Fedora side, the issue seems to be down to Fedora conventions. At any rate, the bug would be in `electron-builder`, not Wire itself.

**Comment by ffflorian** [comment]
> At any rate, the bug would be in electron-builder, not Wire itself.

Exactly.

**Comment by ffflorian** [comment]
@1div0 Closing this one for now. Feel free to reopen if the problem persists.
