### ISSUE TITLE
Looking for help making .deb packages

### ISSUE THREAD

**Issue by ConorIA** [wireapp/wire-desktop#56]
Hi, I've been trying to package up Debian packages using Docker running an Ubuntu image. I can compile packages ok, but when I install and try to run them under a virtual machine, I get the following error: 

```
./Wire
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'minimist'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/conor/Wire-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/conor/Wire-linux-x64/resources/app.asar/main.js:25:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

I also tried running the build commands on Ubuntu and tarballing the /build directory. I brought these files over to my Manjaro install, but unfortunately the ./Wire command gives the same error. I think that something is missing in my build script. 

I am almost certain that something is missing in my build environment. To test this, I copied some [Arch packages](http://conoria.gitlab.io/wire-pkgbuilds/) that I had made on Docker using my manjaro-base image, I extracted them on Ubuntu in a virtual machine, and wire could run fine from those builds. 

This isn't an issue with Wire as such, but there might be a dependency or something missing that should be checked for in the code. My tests are over on [Gitlab](https://gitlab.com/ConorIA/wire-tests). The CI is [configured](https://gitlab.com/ConorIA/wire-tests/blob/master/.gitlab-ci.yml) to run this [build script](https://gitlab.com/ConorIA/wire-tests/snippets/26519).

**Comment by lipis** [comment]
#63

**Comment by ConorIA** [comment]
Alright! I'll keep maintaining the Arch PKGBUILD while you folks take care of Debian-based distros for now!

**Comment by lipis** [comment]
We might need your help and experience there as well.. so stay tuned :D
