### ISSUE TITLE
Cannot find module '../screen'

### ISSUE THREAD

**Issue by epocopa** [wireapp/wire-desktop#597]
Just switched to the apt repo and wire opens but I get a Javascript error:

> Uncaught Exception:
Error: Cannot find module '../screen'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/wire-desktop/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as screen] (/opt/wire-desktop/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at Object.isInView (/opt/wire-desktop/resources/app/js/util.js:30:35)
    at showMainWindow (/opt/wire-desktop/resources/app/main.js:230:15)
    at App.<anonymous> (/opt/wire-desktop/resources/app/main.js:364:3)
    at emitTwo (events.js:111:20)

Btw my system is ElementaryOS Loki based on Ubuntu 16.04 LTS

**Comment by ConorIA** [comment]
See #590 and #467.
There is a workaround in #593.

**Comment by epocopa** [comment]
Oh, I just saw #467
I searched for duplicates but didn´t appear anything with 'screen' in the tittle

**Comment by gregor** [comment]
I renamed the linked issue for easier discoverability
