### ISSUE TITLE
[Linux] Application fails to start.

### ISSUE THREAD

**Issue by alex-five** [wireapp/wire-desktop#606]
When I try to start the app I get the following error:
```
user@host:~$ /opt/wire-desktop/wire-desktop 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (/opt/wire-desktop/resources/app/main.js:95:36)
    at Object.<anonymous> (/opt/wire-desktop/resources/app/main.js:377:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/opt/wire-desktop/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/wire-desktop/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)

```
The console stays busy till I press Ctrl+C.

App was installed from debian repository "deb https://wire-app.wire.com/linux/debian stable main"

Debian 9 (stretch) + i3 window manager + Firefox 45.8.0 (+NoScript)
```
user@host:~$ uname -a
Linux host 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux
```

**Comment by xeppaka** [comment]
After updating to the latest version have the same issue.
```[nnm@PKA ~]$ wire-desktop
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (/opt/wire-desktop/resources/app/main.js:95:36)
    at Object.<anonymous> (/opt/wire-desktop/resources/app/main.js:377:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/opt/wire-desktop/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/wire-desktop/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
```
```Linux PKA 4.10.11-1-ARCH #1 SMP PREEMPT Tue Apr 18 08:39:42 CEST 2017 x86_64 GNU/Linux```

**Comment by herrmannplatz** [comment]
should be fixed with #587. we are preparing a new linux release

**Comment by aquatooth** [comment]
@herrmannplatz Wow, your team is working faster, look forward to testing the new Linux release!
Thanks team.

**Comment by ffflorian** [comment]
@aquatooth Closing this since the error is fixed. :slightly_smiling_face: Feel free to reopen this issue if the error persists.

**Comment by alex-five** [comment]
@herrmannplatz, @ffflorian

Thanks, that really was fast :) Could you indicate the version number in which it will be fixed to avoid confusion?

**Comment by ffflorian** [comment]
@alex-five It will be in 2.13.2741, you can update it via `apt-get`.
