### ISSUE TITLE
neon ERR! Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by holic-cl** [wireapp/wire-desktop#766]
Wire Version: cloned from master branch (99fd35c)
OS: Debian GNU/Linux 9.0 (stretch)
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. git clone
2. npm install

What is the expected result?
install all the dependencies

What happens instead?
Error thrown
neon ERR! Cannot read property 'toString' of null

```
neon ERR! Cannot read property 'toString' of null

TypeError: Cannot read property 'toString' of null
    at Function.BuildSettings.current (/home/holic/dev/holic-labs/wire-desktop/electron/node_modules/neon-cli/dist/neon-cli/build-settings.js:29:13)
    at Project.<anonymous> (/home/holic/dev/holic-labs/wire-desktop/electron/node_modules/neon-cli/dist/neon-cli/project.js:59:61)
    at step (/home/holic/dev/holic-labs/wire-desktop/electron/node_modules/neon-cli/dist/neon-cli/project.js:32:23)
    at Object.next (/home/holic/dev/holic-labs/wire-desktop/electron/node_modules/neon-cli/dist/neon-cli/project.js:13:53)
    at /home/holic/dev/holic-labs/wire-desktop/electron/node_modules/neon-cli/dist/neon-cli/project.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/home/holic/dev/holic-labs/wire-desktop/electron/node_modules/neon-cli/dist/neon-cli/project.js:3:12)
    at Project.build (/home/holic/dev/holic-labs/wire-desktop/electron/node_modules/neon-cli/dist/neon-cli/project.js:53:16)
    at Object.<anonymous> (/home/holic/dev/holic-labs/wire-desktop/electron/node_modules/neon-cli/dist/neon-cli/ops/neon_build.js:46:50)
    at step (/home/holic/dev/holic-labs/wire-desktop/electron/node_modules/neon-cli/dist/neon-cli/ops/neon_build.js:32:23)
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
```

Don't know if i need additional dependencies on my system:
```
libsodium-dev:amd64                                         1.0.11-2
libsodium18:amd64                                           1.0.11-2
libneon27:amd64                                             0.30.2-2
libneon27-dev                                               0.30.2-2
libneon27-gnutls:amd64                                      0.30.2-2
```

**Comment by ConorIA** [comment]
You need rust and cargo installed to compile libsodium-neon.

**Comment by holic-cl** [comment]
Ok, thanks, i just installed and it works now.
